# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    - image: circleci/node:9 # similar to the Dockerfile version

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download, install and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run tests!
      - run: yarn run test-ci

      # TODO: Build and verify the build

      - persist_to_workspace:
          root: .
          paths:
            - '*'

  rancher deploy:
    docker:
      - image: pstauffer/curl:latest
    steps:
      - run: curl -gX POST $DEPLOY_TRIGGER_URL$CIRCLE_SHA1

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - rancher deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
