# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    - image: circleci/node:6 # Lambda = 6.10.3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download, install and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run tests!
      - run: yarn run test-ci

      # Build and verify the build
      - run: yarn run build:prod -- --colors
      - run: node scripts/testLambdaHandlers.js

      - persist_to_workspace:
          root: dist
          # Must be relative path from root
          paths:
            - '*'

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: dist
      - run: ls -l dist
      #- run: yarn run serverless config credentials --provider aws --key $X_AWS_ACCESS_KEY_ID --secret $X_AWS_SECRET_ACCESS_KEY
      #- run: yarn run serverless deploy

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
#          filters:
#            branches:
#              only:
#                - master
