service: graphql-proxy

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1 # EU (Ireland)
  timeout: 20 # The default is 6

package:
  exclude:
    - ./**
  include:
    - dist/lambda.js

functions:
  api:
    handler: dist/lambda.graphql
    environment:
      OPTICS_API_KEY: ${env:OPTICS_API_KEY}
    events:
      - http:
          path: /
          method: POST
          cors: true # needed for GraphiQL
          integration: lambda-proxy
