service: graphql-proxy

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1 # EU (Ireland)
  timeout: 20 # The default is 6

package:
  exclude:
    - ./**
  include:
    - dist/lambda.js

functions:
  api:
    handler: dist/lambda.graphql
    environment:
      BOOKING_COM_TOKEN: ${env:BOOKING_COM_TOKEN}
      ALGOLIA_APP_ID: ${env:ALGOLIA_APP_ID}
      ALGOLIA_API_KEY: ${env:ALGOLIA_API_KEY}
    events:
      - http:
          path: /
          method: POST
          cors: true # needed for GraphiQL
          integration: lambda-proxy

# MANUALLY CREATED RESOURCES:
#
# N. Virginia
#   Certificate Manager:
#     - approved domain: graphql.kiwi.com
#     - approved domain: *.graphql.kiwi.com
#
# Ireland:
#   API Gateway:
#     - custom domain: graphql.kiwi.com
#
# Global:
#   Route 53:
#     - hosted zone: graphql.kiwi.com
#         A: graphql.kiwi.com. (alias pointing to the CloudFront CDN created by API Gateway)
